cabal-version:      3.12
name:               rofi-hoogle-hs
version:            0.1.0.0
synopsis:           Query Hoogle from Rofi

-- A longer description of the package.
-- description:
homepage:           github.com/rebeccaskinner/rofi-hoogle

-- A URL where users can report bugs.
-- bug-reports:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Rebecca Skinner
maintainer:         rebecca@rebeccaskinner.net

-- A copyright notice.
-- copyright:
category:           Development
extra-source-files: CHANGELOG.md

library
    build-depends:  base
                  , hoogle
                  , bytestring
                  , containers
                  , aeson
                  , directory
                  , filepath
                  , stm
                  , text
                  , html-entities
    exposed-modules: HoogleQuery
                   , HoogleQuery.SearchHoogle
                   , HoogleQuery.Config
                   , HoogleQuery.ResultSorting
                   , PangoUtils

    hs-source-dirs: src
    default-language: GHC2024

foreign-library rofi-hoogle-native
    type:             native-shared
    lib-version-info: 0:0:0

    other-modules:    HoogleQuery.Native
                    , HoogleQuery.SearchHoogle
                    , HoogleQuery.Config
                    , HoogleQuery.ResultSorting
                    , PangoUtils

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base
                    , rofi-hoogle-hs
                    , hoogle
                    , bytestring
                    , containers
                    , aeson
                    , directory
                    , filepath
                    , stm
                    , text
                    , html-entities
    hs-source-dirs:   src
    c-sources:        csrc/wrapper.c
    default-language: GHC2024

test-suite rofi-hoogle-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    other-modules:    Gen
                    , HoogleQuery.ConfigSpec
                    , HoogleQuery.ResultSortingSpec
    build-depends:    base
                    , rofi-hoogle-hs
                    , hoogle
                    , aeson
                    , bytestring
                    , containers
                    , filepath
                    , hedgehog
                    , hspec
                    , hspec-hedgehog
                    , temporary
    hs-source-dirs:   test
    default-language: GHC2024
